[package]
name = "gitfilter"
version = "0.1.0"
authors = ["nikita-skobov"]
edition = "2018"


[dependencies]
gumdrop = { path = "../gumdrop" }
die = { path = "../die" }
exechelper = { path = "../exechelper" }
num_cpus = "1.13.0"
# rayon = "*"
regex = "1.4.3"
once_cell = "*"
